### ISSUE TITLE
Using with pygmentize?

### ISSUE THREAD

**Issue by reagle** [jhermann/pygments-markdown-lexer#4]
I'd like to pretty print a markdown source file, and hoped I could use this lexer but it still isn't listed as an option after a pip install.

**Comment by jhermann** [comment]
There is still a lot missing and no release, see installing from source @

https://github.com/jhermann/pygments-markdown-lexer#installation

**Comment by jhermann** [comment]
Cannot reproduce…

```
$ pygmentize -L | grep markdown
* md, markdown:
    Markdown (filenames *.md, *.mkd, *.markdown)
```

Please try again with current HEAD and all 'dev-requirements', and reopen with more info if it still fails for you.
