### ISSUE TITLE
Sphinx: extension 'pygments_markdown_lexer' has no setup() function; is it really a Sphinx extension module?

### ISSUE THREAD

**Issue by honzajavorek** [jhermann/pygments-markdown-lexer#6]
Hello, if I use `pygments_markdown_lexer` like this in Sphinx `conf.py`:

``` python
# -- General configuration ------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.intersphinx',
    'pygments_markdown_lexer',
]
```

I get the warning from title. Since I promote warnings to errors on CI to check whether the docs build is all correct, I'd like this warning to go away. What can I do about it?

**Comment by jhermann** [comment]
Seems Sphinx wants a call to [Sphinx::add_lexer](http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_lexer) from the `setup` function. Either I always ignored that warning, or it's only in newer versions of Sphinx.

**Comment by honzajavorek** [comment]
Thanks for fixing!

**Comment by honzajavorek** [comment]
@jhermann Did you happen to have time to release this change?
